const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const COLORS = ['#eee9ff','#e5f7ef','#fff0e4','#e5f4ff','#ffeaf1'];
const EMOJIS = {Alimentação:'🍜',Transporte:'🚕',Hospedagem:'🛏️',Casa:'🏠',Lazer:'🎟️',Outros:'🧾'};
const currencyNames = {BRL:'Real brasileiro',USD:'Dólar americano',EUR:'Euro',GBP:'Libra esterlina',ARS:'Peso argentino',JPY:'Iene japonês'};
const today = () => new Date().toISOString().slice(0,10);
const uid = () => Math.random().toString(36).slice(2,10);
const fmt = (n,c='BRL') => new Intl.NumberFormat('pt-BR',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(n)||0);
const safe = s => String(s ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials = s => String(s||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const seed = {
 groups:[
  {id:'g-trip',name:'Viagem a Pipa',currency:'BRL',members:['Gabrielly','Alex','Bia','Lucas'],emoji:'🏝️',color:COLORS[0]},
  {id:'g-home',name:'Casa compartilhada',currency:'BRL',members:['Gabrielly','Alex','Marina'],emoji:'🏡',color:COLORS[1]},
  {id:'g-weekend',name:'Fim de semana',currency:'BRL',members:['Gabrielly','Bia','Lucas'],emoji:'🎉',color:COLORS[2]}
 ],
 expenses:[
  {id:'e1',groupId:'g-trip',description:'Mercado para a viagem',amount:246.8,currency:'BRL',baseAmount:246.8,payer:'Alex',participants:['Gabrielly','Alex','Bia','Lucas'],shares:{Gabrielly:61.7,Alex:61.7,Bia:61.7,Lucas:61.7},category:'Alimentação',date:'2026-10-08'},
  {id:'e2',groupId:'g-trip',description:'Combustível',amount:180,currency:'BRL',baseAmount:180,payer:'Gabrielly',participants:['Gabrielly','Alex','Lucas'],shares:{Gabrielly:60,Alex:60,Lucas:60},category:'Transporte',date:'2026-10-07'},
  {id:'e3',groupId:'g-trip',description:'Hospedagem',amount:720,currency:'BRL',baseAmount:720,payer:'Bia',participants:['Gabrielly','Alex','Bia','Lucas'],shares:{Gabrielly:180,Alex:180,Bia:180,Lucas:180},category:'Hospedagem',date:'2026-10-06'},
  {id:'e4',groupId:'g-home',description:'Compras da semana',amount:315.4,currency:'BRL',baseAmount:315.4,payer:'Marina',participants:['Gabrielly','Alex','Marina'],shares:{Gabrielly:105.13,Alex:105.13,Marina:105.14},category:'Casa',date:'2026-10-08'},
  {id:'e5',groupId:'g-home',description:'Conta de internet',amount:119.9,currency:'BRL',baseAmount:119.9,payer:'Gabrielly',participants:['Gabrielly','Alex','Marina'],shares:{Gabrielly:39.96,Alex:39.97,Marina:39.97},category:'Casa',date:'2026-10-04'},
  {id:'e6',groupId:'g-weekend',description:'Jantar de sábado',amount:168,currency:'BRL',baseAmount:168,payer:'Lucas',participants:['Gabrielly','Bia','Lucas'],shares:{Gabrielly:56,Bia:56,Lucas:56},category:'Alimentação',date:'2026-10-03'}
 ],
 payments:[{id:'p1',groupId:'g-trip',from:'Gabrielly',to:'Alex',amount:30,date:'2026-10-08'}],
 activeGroupId:'g-trip'
};
let data = loadData(), currentView='overview', pendingPayment=null, toastTimer;
function loadData(){try{const saved=localStorage.getItem('dividi-data-v1');return saved?JSON.parse(saved):structuredClone(seed)}catch{return structuredClone(seed)}}
function persist(){localStorage.setItem('dividi-data-v1',JSON.stringify(data))}
function group(id){return data.groups.find(g=>g.id===id)}
function activeGroup(){return group(data.activeGroupId)||data.groups[0]}
function expensesFor(gid){return data.expenses.filter(e=>!gid||e.groupId===gid)}
function membersFor(gid){return group(gid)?.members||[]}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function setView(view){currentView=view;$$('.page').forEach(p=>p.classList.add('hidden'));$('#'+view+'-view').classList.remove('hidden');$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#breadcrumb-title').textContent=({overview:'Visão geral',expenses:'Despesas',settlements:'Acertos de contas'})[view]||'Visão geral';$('#sidebar').classList.remove('open');if(view==='expenses')renderExpenses();if(view==='settlements')renderSettlements();window.scrollTo({top:0,behavior:'smooth'})}
function netBalances(gid){const g=group(gid);if(!g)return {};const b=Object.fromEntries(g.members.map(m=>[m,0]));expensesFor(gid).forEach(e=>{const amount=Number(e.baseAmount)||0;if(!(e.payer in b))b[e.payer]=0;b[e.payer]+=amount;Object.entries(e.shares||{}).forEach(([m,v])=>{if(!(m in b))b[m]=0;b[m]-=Number(v)||0})});data.payments.filter(p=>p.groupId===gid).forEach(p=>{if(!(p.from in b))b[p.from]=0;if(!(p.to in b))b[p.to]=0;b[p.from]+=Number(p.amount);b[p.to]-=Number(p.amount)});Object.keys(b).forEach(k=>{b[k]=Math.round(b[k]*100)/100});return b}
function optimizeSettlements(gid){const balances=netBalances(gid);const debtors=Object.entries(balances).filter(([,v])=>v<-.005).map(([name,v])=>({name,amount:-v})).sort((a,b)=>b.amount-a.amount);const creditors=Object.entries(balances).filter(([,v])=>v>.005).map(([name,v])=>({name,amount:v})).sort((a,b)=>b.amount-a.amount);const out=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const amount=Math.round(Math.min(debtors[i].amount,creditors[j].amount)*100)/100;if(amount>.005)out.push({from:debtors[i].name,to:creditors[j].name,amount});debtors[i].amount=Math.round((debtors[i].amount-amount)*100)/100;creditors[j].amount=Math.round((creditors[j].amount-amount)*100)/100;if(debtors[i].amount<.005)i++;if(creditors[j].amount<.005)j++}return out}
function myNet(){return data.groups.reduce((sum,g)=>sum+(netBalances(g.id).Gabrielly||0),0)}
function renderSidebar(){const list=$('#group-list');list.innerHTML=data.groups.map(g=>`<button class="group-nav ${g.id===data.activeGroupId?'selected':''}" data-group="${g.id}"><span class="group-dot" style="background:${g.color||COLORS[0]}"></span><span class="group-name">${safe(g.name)}</span><span class="group-total">${g.members.length}</span></button>`).join('');$$('[data-group]').forEach(b=>b.addEventListener('click',()=>{data.activeGroupId=b.dataset.group;persist();renderAll()}))}
function renderOverview(){const g=activeGroup(), es=expensesFor(g?.id);const total=es.reduce((s,e)=>s+(Number(e.baseAmount)||0),0);const balances=netBalances(g?.id);const mine=balances.Gabrielly||0;$('#my-balance').textContent=(myNet()>=0?'+ ':'− ')+fmt(Math.abs(myNet()),'BRL');$('#balance-caption').textContent=myNet()>=0?'Você tem a receber nos grupos':'Você tem a pagar nos grupos';$('#group-total').textContent=fmt(total,g?.currency||'BRL');$('#group-count').textContent=`${g?.name||'Grupo'} · ${es.length} despesas`;$('#owed-to-me').textContent=fmt(Math.max(0,mine),'BRL');$('#i-owe').textContent=fmt(Math.max(0,-mine),'BRL');
 const groupCards=$('#group-cards');groupCards.innerHTML=data.groups.map(g=>{const total=expensesFor(g.id).reduce((s,e)=>s+e.baseAmount,0);const bal=netBalances(g.id).Gabrielly||0;return `<button class="group-card" data-open-group="${g.id}"><div class="group-card-top"><span class="group-emoji" style="background:${g.color||COLORS[0]}">${g.emoji||'👥'}</span><div style="min-width:0"><div class="group-card-title">${safe(g.name)}</div><div class="group-card-members">${g.members.length} participantes</div></div></div><div class="group-card-bottom"><div><small>Despesas registradas</small><strong>${fmt(total,g.currency)}</strong></div><span class="group-card-status">${bal>=0?'A receber':'A pagar'}</span></div></button>`}).join('');$$('[data-open-group]').forEach(b=>b.onclick=()=>{data.activeGroupId=b.dataset.openGroup;persist();renderAll()});
 const settlements=optimizeSettlements(g?.id).slice(0,3);$('#settlement-preview').innerHTML=settlements.length?settlements.map(s=>`<div class="settlement-row"><span class="person-avatar">${initials(s.from)}</span><div class="settlement-person"><strong>${safe(s.from)}</strong><br>paga para <strong>${safe(s.to)}</strong></div><span class="settlement-amount">${fmt(s.amount,g.currency)}</span></div>`).join(''):'<div class="empty-note">Tudo equilibrado por aqui. Nenhum acerto pendente.</div>';
 const recent=[...data.expenses].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('#recent-expenses').innerHTML=recent.map(e=>{const g=group(e.groupId);return `<tr><td><div class="expense-title"><span class="category-icon">${EMOJIS[e.category]||'🧾'}</span>${safe(e.description)}</div></td><td class="table-group">${safe(g?.name||'Grupo removido')}</td><td>${safe(e.payer)}</td><td>${formatDate(e.date)}</td><td class="table-amount">${fmt(e.baseAmount,g?.currency||'BRL')}</td></tr>`}).join('')||'<tr><td colspan="5" class="empty-note">Ainda não há despesas.</td></tr>';
}
function formatDate(s){if(!s)return '—';return new Date(s+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).replace('.','')}
function renderExpenses(){const q=$('#search-expenses').value.toLowerCase(),cat=$('#filter-category').value,mem=$('#filter-member').value,date=$('#filter-date').value;const filtered=[...data.expenses].filter(e=>(!q||e.description.toLowerCase().includes(q)||e.payer.toLowerCase().includes(q))&&(!cat||e.category===cat)&&(!mem||e.payer===mem||e.participants.includes(mem))&&(!date||e.date>=date)).sort((a,b)=>b.date.localeCompare(a.date));$('#expenses-table').innerHTML=filtered.map(e=>{const g=group(e.groupId);return `<tr><td><div class="expense-title"><span class="category-icon">${EMOJIS[e.category]||'🧾'}</span>${safe(e.description)}</div></td><td>${safe(g?.name||'—')}</td><td>${safe(e.category)}</td><td>${safe(e.payer)}</td><td>${formatDate(e.date)}</td><td class="table-amount">${fmt(e.baseAmount,g?.currency||'BRL')}</td></tr>`}).join('');$('#empty-expenses').classList.toggle('hidden',filtered.length>0)}
function renderSettlements(){const g=activeGroup();const list=optimizeSettlements(g?.id);$('#settlement-list').innerHTML=list.length?list.map(s=>`<div class="settlement-item"><div class="settlement-route"><span class="person-avatar">${initials(s.from)}</span><div><div class="route-names"><strong>${safe(s.from)}</strong><span class="route-line">→</span><strong>${safe(s.to)}</strong></div><div class="route-sub">${safe(g.name)} · sugestão de acerto</div></div></div><div class="settlement-actions"><strong>${fmt(s.amount,g.currency)}</strong><button class="primary-button" data-pay-from="${safe(s.from)}" data-pay-to="${safe(s.to)}" data-pay-amount="${s.amount}">Registrar pagamento</button></div></div>`).join(''):'<div class="empty-note">Nenhum acerto pendente neste grupo. Os saldos estão equilibrados.</div>';
 $$('[data-pay-from]').forEach(b=>b.onclick=()=>openPayment(b.dataset.payFrom,b.dataset.payTo,Number(b.dataset.payAmount)));
 const payments=data.payments.filter(p=>p.groupId===g?.id).sort((a,b)=>b.date.localeCompare(a.date));$('#payment-history').innerHTML=payments.length?payments.map(p=>`<div class="payment-line"><div><strong>${safe(p.from)} pagou ${safe(p.to)}</strong><small>${formatDate(p.date)} · ${safe(g.name)}</small></div><span class="paid-tag">${fmt(p.amount,g.currency)} registrado</span></div>`).join(''):'<div class="empty-note">Os pagamentos registrados aparecerão aqui.</div>'}
function renderAll(){renderSidebar();renderOverview();renderExpenses();renderSettlements();populateGroupSelects();persist()}
function populateGroupSelects(){const opts=data.groups.map(g=>`<option value="${g.id}">${safe(g.name)}</option>`).join('');$('#expense-group').innerHTML=opts;$('#expense-group').value=activeGroup()?.id||data.groups[0]?.id||'';refreshExpensePeople();const all=[...new Set(data.groups.flatMap(g=>g.members))].sort();$('#filter-member').innerHTML='<option value="">Todos os membros</option>'+all.map(m=>`<option>${safe(m)}</option>`).join('')}
function refreshExpensePeople(){const g=group($('#expense-group').value);const old=[...$$('#expense-members input:checked')].map(i=>i.value);$('#expense-payer').innerHTML=(g?.members||[]).map(m=>`<option>${safe(m)}</option>`).join('');$('#expense-members').innerHTML=(g?.members||[]).map((m,i)=>`<label class="member-chip"><input type="checkbox" value="${safe(m)}" checked> ${safe(m)}</label>`).join('');if(old.length){$$('#expense-members input').forEach(i=>i.checked=old.includes(i.value))}renderSplitDetails()}
function selectedMembers(){return $$('#expense-members input:checked').map(i=>i.value)}
function renderSplitDetails(){const type=$('#split-type').value;const people=selectedMembers();const amount=Number($('#expense-amount').value)||0;const box=$('#split-details');if(type==='equal'){box.innerHTML=`<div class="split-summary">Divisão igual entre ${people.length} ${people.length===1?'pessoa':'pessoas'} · ${fmt(people.length?amount/people.length:0,$('#expense-currency').value)} por pessoa (aprox.)</div>`;return}const old={};$$('[data-split-member]').forEach(i=>old[i.dataset.splitMember]=i.value);box.innerHTML=people.map(m=>`<div class="split-detail-row"><span>${safe(m)}</span><input data-split-member="${safe(m)}" type="number" min="0" step="${type==='percent'?'0.01':'0.01'}" required value="${old[m]??(type==='percent'?(people.length?100/people.length:0).toFixed(2):type==='shares'?'1':(people.length?amount/people.length:0).toFixed(2))}" aria-label="${safe(m)} ${type==='exact'?'valor':type==='percent'?'percentual':'quotas'}"></div>`).join('')+`<div class="split-summary" id="split-validation"></div>`;$$('[data-split-member]').forEach(i=>i.addEventListener('input',updateSplitSummary));updateSplitSummary()}
function updateSplitSummary(){const type=$('#split-type').value,inputs=$$('[data-split-member]');const total=inputs.reduce((s,i)=>s+(Number(i.value)||0),0);const amount=Number($('#expense-amount').value)||0;let msg='';if(type==='exact')msg=`Soma: ${fmt(total,$('#expense-currency').value)} de ${fmt(amount,$('#expense-currency').value)} · ${Math.abs(total-amount)<.011?'valores conferem':'a soma precisa ser igual à despesa'}`;if(type==='percent')msg=`Total: ${total.toFixed(2)}% · ${Math.abs(total-100)<.011?'percentagens conferem':'o total precisa ser 100%'}`;if(type==='shares')msg=`Total: ${total.toFixed(2)} quotas · cada quota equivale a ${fmt(total?amount/total:0,$('#expense-currency').value)}`;$('#split-validation').textContent=msg;$('#split-validation').style.color=(type==='exact'?Math.abs(total-amount)<.011:type==='percent'?Math.abs(total-100)<.011:total>0)?'var(--green)':'var(--red)'}
function showModal(id){$('#'+id).classList.remove('hidden');const first=$('input:not([type=checkbox]),select,textarea',$('#'+id));if(first)setTimeout(()=>first.focus(),50)}
function closeModals(){$$('.modal-backdrop').forEach(m=>m.classList.add('hidden'))}
function openExpense(){if(!data.groups.length){showToast('Crie um grupo antes de adicionar despesas.');openGroup();return}$('#expense-form').reset();$('#expense-date').value=today();$('#expense-group').value=activeGroup().id;$('#expense-currency').value=activeGroup().currency;refreshExpensePeople();$('#expense-error').classList.add('hidden');updateConversionNote();showModal('expense-modal')}
function updateConversionNote(){const c=$('#expense-currency').value,g=group($('#expense-group').value);$('#conversion-note').textContent=c===(g?.currency||'BRL')?`A despesa será registrada em ${g?.currency||'BRL'}, a moeda padrão do grupo.`:`A taxa de ${c} para ${g?.currency||'BRL'} será consultada na API Frankfurter ao salvar. Se a API estiver indisponível, a despesa não será salva com uma taxa inventada.`}
async function getRate(from,to,date){if(from===to)return {rate:1,date:date||today(),source:'mesma moeda'};const endpoint=date?`https://api.frankfurter.app/${date}?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`:`https://api.frankfurter.app/latest?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`;const r=await fetch(endpoint);if(!r.ok)throw new Error('A API de câmbio não retornou uma taxa para essas moedas.');const j=await r.json();const rate=j.rates?.[to];if(!rate)throw new Error('Não foi possível obter uma taxa para esse par de moedas.');return {rate,date:j.date||date||today(),source:'Frankfurter API'}}
function calculateShares(amount,people,type){if(!people.length)throw new Error('Selecione pelo menos uma pessoa.');let values={};if(type==='equal'){const cents=Math.round(amount*100),each=Math.floor(cents/people.length);let remainder=cents-each*people.length;people.forEach(m=>{values[m]=(each+(remainder-->0?1:0))/100})}else{const nums=$$('[data-split-member]').map(i=>Number(i.value)||0);if(nums.some(n=>n<0))throw new Error('Os valores da divisão não podem ser negativos.');const total=nums.reduce((a,b)=>a+b,0);if(type==='exact'){if(Math.abs(total-amount)>.01001)throw new Error('A soma dos valores precisa ser igual ao total da despesa.');people.forEach((m,i)=>values[m]=Math.round(nums[i]*100)/100)}else if(type==='percent'){if(Math.abs(total-100)>.01001)throw new Error('As percentagens precisam somar 100%.');let cents=Math.round(amount*100),used=0;people.forEach((m,i)=>{const c=i===people.length-1?cents-used:Math.round(cents*nums[i]/100);values[m]=c/100;used+=c})}else if(type==='shares'){if(total<=0)throw new Error('O total de quotas precisa ser maior que zero.');let cents=Math.round(amount*100),used=0;people.forEach((m,i)=>{const c=i===people.length-1?cents-used:Math.round(cents*nums[i]/total);values[m]=c/100;used+=c})}}return values}
$('#expense-form').addEventListener('submit',async ev=>{ev.preventDefault();const err=$('#expense-error'),btn=$('#save-expense');err.classList.add('hidden');try{const g=group($('#expense-group').value),amount=Number($('#expense-amount').value),people=selectedMembers();if(!g)throw new Error('Selecione um grupo.');if(!(amount>0))throw new Error('Informe um valor maior que zero.');if(!people.length)throw new Error('Selecione pelo menos um participante.');const currency=$('#expense-currency').value,type=$('#split-type').value;const shares=calculateShares(amount,people,type);btn.disabled=true;btn.textContent='Consultando câmbio…';const fx=await getRate(currency,g.currency,$('#expense-date').value);const baseAmount=Math.round(amount*fx.rate*100)/100;const convertedShares={};Object.entries(shares).forEach(([m,v])=>convertedShares[m]=Math.round(v*fx.rate*100)/100);const shareTotal=Object.values(convertedShares).reduce((a,b)=>a+b,0);if(Math.abs(shareTotal-baseAmount)>.02)throw new Error('A conversão gerou uma diferença de arredondamento. Tente novamente.');data.expenses.push({id:uid(),groupId:g.id,description:$('#expense-description').value.trim(),amount,currency,baseAmount,payer:$('#expense-payer').value,participants:people,shares:convertedShares,category:$('#expense-category').value,date:$('#expense-date').value,fxRate:fx.rate,fxDate:fx.date,fxSource:fx.source,splitType:type});data.activeGroupId=g.id;persist();closeModals();renderAll();showToast(`Despesa salva. Taxa ${currency}/${g.currency}: ${fx.rate.toFixed(4)} (${fx.date}).`)}catch(e){err.textContent=e.message||'Não foi possível salvar a despesa.';err.classList.remove('hidden')}finally{btn.disabled=false;btn.textContent='Salvar despesa'}});
function openGroup(){ $('#group-form').reset();$('#group-error').classList.add('hidden');showModal('group-modal')}
$('#group-form').addEventListener('submit',ev=>{ev.preventDefault();const name=$('#group-name').value.trim(),members=[...new Set($('#group-members-input').value.split(',').map(x=>x.trim()).filter(Boolean))],err=$('#group-error');if(members.length<2){err.textContent='Adicione pelo menos duas pessoas, separadas por vírgula.';err.classList.remove('hidden');return}if(members.length>30){err.textContent='Para manter a divisão clara, adicione até 30 participantes por grupo.';err.classList.remove('hidden');return}const g={id:uid(),name,currency:$('#group-currency').value,members,emoji:'👥',color:COLORS[data.groups.length%COLORS.length]};data.groups.push(g);data.activeGroupId=g.id;persist();closeModals();renderAll();showToast('Grupo criado com sucesso.')});
function openPayment(from,to,amount){pendingPayment={from,to,amount,groupId:activeGroup().id};$('#payment-explainer').textContent=`${from} vai pagar ${to}. Valor sugerido: ${fmt(amount,activeGroup().currency)}. Você pode registrar um pagamento parcial.`;$('#payment-amount').value=amount.toFixed(2);$('#payment-amount').max=amount;$('#payment-date').value=today();$('#payment-error').classList.add('hidden');showModal('payment-modal')}
$('#payment-form').addEventListener('submit',ev=>{ev.preventDefault();const err=$('#payment-error'),amount=Number($('#payment-amount').value);if(!pendingPayment)return;if(!(amount>0)){err.textContent='Informe um valor maior que zero.';err.classList.remove('hidden');return}if(amount>pendingPayment.amount+.01){err.textContent='O valor não pode superar o saldo sugerido. Para registrar outro pagamento, atualize primeiro os saldos.';err.classList.remove('hidden');return}data.payments.push({id:uid(),groupId:pendingPayment.groupId,from:pendingPayment.from,to:pendingPayment.to,amount:Math.round(amount*100)/100,date:$('#payment-date').value});persist();closeModals();renderAll();showToast('Pagamento registrado e saldos atualizados.');pendingPayment=null});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#quick-add').onclick=openExpense;$('#expense-add').onclick=openExpense;$('#add-group-btn').onclick=openGroup;$('#see-groups').onclick=()=>{$('#sidebar').classList.add('open')};$('#expense-group').addEventListener('change',()=>{refreshExpensePeople();$('#expense-currency').value=activeGroup()?.currency||'BRL';updateConversionNote()});$('#split-type').addEventListener('change',renderSplitDetails);$('#expense-amount').addEventListener('input',renderSplitDetails);$('#expense-currency').addEventListener('change',updateConversionNote);$('#expense-members').addEventListener('change',renderSplitDetails);['search-expenses','filter-category','filter-member','filter-date'].forEach(id=>$('#'+id).addEventListener('input',renderExpenses));$('#mobile-menu').onclick=()=>$('#sidebar').classList.toggle('open');$$('.close-modal').forEach(b=>b.addEventListener('click',closeModals));$$('.modal-backdrop').forEach(back=>back.addEventListener('click',e=>{if(e.target===back)closeModals()}));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});$('#reset-demo').onclick=()=>{if(confirm('Restaurar os dados de demonstração? Suas alterações locais serão apagadas.')){data=structuredClone(seed);persist();renderAll();showToast('Demonstração restaurada.')}};
$('#today-label').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();
renderAll();
